import { MigrationInterface, QueryRunner } from "typeorm";

export class ChangeToSnakeCase1695785312624 implements MigrationInterface {
    name = 'ChangeToSnakeCase1695785312624'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`car_cities\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`car_cities\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`car_cities\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`order-details\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`order-details\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`order-details\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`car_languages\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`car_languages\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`car_languages\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`languages\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`languages\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`languages\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`car_type_languages\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`car_type_languages\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`car_type_languages\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`car_types\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`car_types\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`car_types\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`car_car_types\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`car_car_types\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`car_car_types\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`cars\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`cars\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`cars\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`favourites\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`favourites\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`favourites\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`tokens\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`tokens\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`tokens\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`promos\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`promos\` DROP COLUMN \`deletedAt\``);
        await queryRunner.query(`ALTER TABLE \`promos\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`car_cities\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`car_cities\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_cities\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`order-details\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`order-details\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`order-details\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_languages\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`car_languages\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_languages\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`languages\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`languages\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`languages\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_type_languages\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`car_type_languages\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_type_languages\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_types\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`car_types\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_types\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_car_types\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`car_car_types\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_car_types\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cars\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cars\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cars\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`favourites\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`favourites\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`favourites\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tokens\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tokens\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tokens\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`promos\` ADD \`deleted_at\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`promos\` ADD \`created_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`promos\` ADD \`updated_at\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`promos\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`promos\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`promos\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`tokens\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`tokens\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`tokens\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`favourites\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`favourites\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`favourites\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`cars\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`cars\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`cars\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`images\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`car_car_types\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`car_car_types\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`car_car_types\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`car_types\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`car_types\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`car_types\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`car_type_languages\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`car_type_languages\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`car_type_languages\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`languages\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`languages\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`languages\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`car_languages\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`car_languages\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`car_languages\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`order-details\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`order-details\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`order-details\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`orders\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`cities\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`car_cities\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`car_cities\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`car_cities\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`promos\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`promos\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`promos\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tokens\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`tokens\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`tokens\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`favourites\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`favourites\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`favourites\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cars\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cars\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cars\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`images\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_car_types\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_car_types\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`car_car_types\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_types\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_types\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`car_types\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_type_languages\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_type_languages\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`car_type_languages\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`languages\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`languages\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`languages\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_languages\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_languages\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`car_languages\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`order-details\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`order-details\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`order-details\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`orders\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`payment_methods\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`cities\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_cities\` ADD \`updatedAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`car_cities\` ADD \`deletedAt\` timestamp(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`car_cities\` ADD \`createdAt\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
    }

}
